
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class WindowHelp
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.Label label17;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.WindowHelp
			this.Name = "BBB.WindowHelp";
			this.Title = global::Mono.Unix.Catalog.GetString ("WindowHelp");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child BBB.WindowHelp.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("работаем над этим...");
			w1.Add (this.label17);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
