
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class SplashScreen
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label lblSplashStatus;
		private global::Gtk.ProgressBar SplashProgress;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.SplashScreen
			this.Name = "BBB.SplashScreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("SplashScreen");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child BBB.SplashScreen.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblSplashStatus = new global::Gtk.Label ();
			this.lblSplashStatus.Name = "lblSplashStatus";
			this.lblSplashStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox1.Add (this.lblSplashStatus);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblSplashStatus]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SplashProgress = new global::Gtk.ProgressBar ();
			this.SplashProgress.Name = "SplashProgress";
			this.vbox1.Add (this.SplashProgress);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SplashProgress]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 450;
			this.DefaultHeight = 126;
			this.Show ();
		}
	}
}
