
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class comboList
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBoxEntry comboboxentry;
		private global::Gtk.Button button_add;
		private global::Gtk.Button button_remove;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.comboList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BBB.comboList";
			// Container child BBB.comboList.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboboxentry = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry.Name = "comboboxentry";
			this.hbox1.Add (this.comboboxentry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxentry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_add = new global::Gtk.Button ();
			this.button_add.CanFocus = true;
			this.button_add.Name = "button_add";
			this.button_add.UseUnderline = true;
			// Container child button_add.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w3.Add (w6);
			w2.Add (w3);
			this.button_add.Add (w2);
			this.hbox1.Add (this.button_add);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_add]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_remove = new global::Gtk.Button ();
			this.button_remove.CanFocus = true;
			this.button_remove.Name = "button_remove";
			this.button_remove.UseUnderline = true;
			// Container child button_remove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w12.Add (w15);
			w11.Add (w12);
			this.button_remove.Add (w11);
			this.hbox1.Add (this.button_remove);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_remove]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboboxentry.Changed += new global::System.EventHandler (this.OnComboboxentry1Changed);
			this.button_add.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
			this.button_remove.Clicked += new global::System.EventHandler (this.OnButtonRemoveClicked);
		}
	}
}
