
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class GUI_Aqsis
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.GUI_Aqsis
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BBB.GUI_Aqsis";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
