
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class fileList
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry entry2;
		private global::Gtk.Button button_open_editor;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.fileList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BBB.fileList";
			// Container child BBB.fileList.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.hbox1.Add (this.entry2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry2]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_open_editor = new global::Gtk.Button ();
			this.button_open_editor.CanFocus = true;
			this.button_open_editor.Name = "button_open_editor";
			this.button_open_editor.UseUnderline = true;
			// Container child button_open_editor.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd-multiple", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w3.Add (w6);
			w2.Add (w3);
			this.button_open_editor.Add (w2);
			this.hbox1.Add (this.button_open_editor);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_open_editor]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button_open_editor.Clicked += new global::System.EventHandler (this.OnButtonOpenEditorClicked);
		}
	}
}
