
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class RegionEditor
	{
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label label5;
		private global::BBB.DrawingRegion drawingregion;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox11;
		private global::Gtk.Label label13;
		private global::BBB.fileOpenDlg fileopendlg1;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Table table3;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.SpinButton spinbutton_x1;
		private global::Gtk.SpinButton spinbutton_x2;
		private global::Gtk.SpinButton spinbutton_y1;
		private global::Gtk.SpinButton spinbutton_y2;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Label label12;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button154;
		private global::Gtk.HScale hscale1;
		private global::Gtk.Button button153;
		private global::Gtk.Button button155;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.RegionEditor
			this.Name = "BBB.RegionEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("Редактор регионов");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child BBB.RegionEditor.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			this.vbox8.BorderWidth = ((uint)(9));
			// Container child vbox8.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
			this.vbox8.Add (this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.drawingregion = new global::BBB.DrawingRegion ();
			this.drawingregion.Name = "drawingregion";
			this.drawingregion.X1 = 0D;
			this.drawingregion.Y1 = 0D;
			this.drawingregion.X2 = 0D;
			this.drawingregion.Y2 = 0D;
			this.vbox8.Add (this.drawingregion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.drawingregion]));
			w3.Position = 1;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Фоновая картинка");
			this.vbox11.Add (this.label13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.label13]));
			w4.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.fileopendlg1 = new global::BBB.fileOpenDlg ();
			this.fileopendlg1.Events = ((global::Gdk.EventMask)(256));
			this.fileopendlg1.Name = "fileopendlg1";
			this.fileopendlg1.CheckType = false;
			this.vbox11.Add (this.fileopendlg1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.fileopendlg1]));
			w5.Position = 1;
			w5.Expand = false;
			this.hbox2.Add (this.vbox11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox11]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox2.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("y1");
			this.table3.Add (this.label10);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("y2");
			this.table3.Add (this.label11);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("x1");
			this.table3.Add (this.label8);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label8]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("x2");
			this.table3.Add (this.label9);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbutton_x1 = new global::Gtk.SpinButton (0D, 6000D, 1D);
			this.spinbutton_x1.CanFocus = true;
			this.spinbutton_x1.Name = "spinbutton_x1";
			this.spinbutton_x1.Adjustment.PageIncrement = 10D;
			this.spinbutton_x1.ClimbRate = 1D;
			this.spinbutton_x1.Numeric = true;
			this.table3.Add (this.spinbutton_x1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbutton_x1]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbutton_x2 = new global::Gtk.SpinButton (0D, 6000D, 1D);
			this.spinbutton_x2.CanFocus = true;
			this.spinbutton_x2.Name = "spinbutton_x2";
			this.spinbutton_x2.Adjustment.PageIncrement = 10D;
			this.spinbutton_x2.ClimbRate = 1D;
			this.spinbutton_x2.Numeric = true;
			this.table3.Add (this.spinbutton_x2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbutton_x2]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbutton_y1 = new global::Gtk.SpinButton (0D, 6000D, 1D);
			this.spinbutton_y1.CanFocus = true;
			this.spinbutton_y1.Name = "spinbutton_y1";
			this.spinbutton_y1.Adjustment.PageIncrement = 10D;
			this.spinbutton_y1.ClimbRate = 1D;
			this.spinbutton_y1.Numeric = true;
			this.table3.Add (this.spinbutton_y1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbutton_y1]));
			w14.LeftAttach = ((uint)(3));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbutton_y2 = new global::Gtk.SpinButton (0D, 6000D, 1D);
			this.spinbutton_y2.CanFocus = true;
			this.spinbutton_y2.Name = "spinbutton_y2";
			this.spinbutton_y2.Adjustment.PageIncrement = 10D;
			this.spinbutton_y2.ClimbRate = 1D;
			this.spinbutton_y2.Numeric = true;
			this.table3.Add (this.spinbutton_y2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbutton_y2]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(3));
			w15.RightAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.table3]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox2.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator2]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Масштаб");
			this.vbox10.Add (this.label12);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label12]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button154 = new global::Gtk.Button ();
			this.button154.CanFocus = true;
			this.button154.Name = "button154";
			this.button154.UseUnderline = true;
			// Container child button154.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-out", global::Gtk.IconSize.Menu);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w20.Add (w23);
			w19.Add (w20);
			this.button154.Add (w19);
			this.hbox3.Add (this.button154);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button154]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hscale1 = new global::Gtk.HScale (null);
			this.hscale1.CanFocus = true;
			this.hscale1.Name = "hscale1";
			this.hscale1.Adjustment.Upper = 100D;
			this.hscale1.Adjustment.PageIncrement = 10D;
			this.hscale1.Adjustment.StepIncrement = 1D;
			this.hscale1.DrawValue = false;
			this.hscale1.Digits = 0;
			this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox3.Add (this.hscale1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hscale1]));
			w28.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button153 = new global::Gtk.Button ();
			this.button153.CanFocus = true;
			this.button153.Name = "button153";
			this.button153.UseUnderline = true;
			// Container child button153.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-in", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w30.Add (w33);
			w29.Add (w30);
			this.button153.Add (w29);
			this.hbox3.Add (this.button153);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button153]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button155 = new global::Gtk.Button ();
			this.button155.CanFocus = true;
			this.button155.Name = "button155";
			this.button155.UseUnderline = true;
			// Container child button155.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-100", global::Gtk.IconSize.Menu);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w39.Add (w42);
			w38.Add (w39);
			this.button155.Add (w38);
			this.hbox3.Add (this.button155);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button155]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			this.vbox10.Add (this.hbox3);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox3]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.hbox2.Add (this.vbox10);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox10]));
			w48.Position = 4;
			this.vbox8.Add (this.hbox2);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox2]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			w1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox8]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Internal child BBB.RegionEditor.ActionArea
			global::Gtk.HButtonBox w51 = this.ActionArea;
			w51.Name = "dialog1_ActionArea";
			w51.Spacing = 10;
			w51.BorderWidth = ((uint)(5));
			w51.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w52 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w51 [this.buttonCancel]));
			w52.Expand = false;
			w52.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w53 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w51 [this.buttonOk]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1102;
			this.DefaultHeight = 779;
			this.Show ();
			this.spinbutton_y2.Changed += new global::System.EventHandler (this.OnSpinbuttonY2Changed);
			this.spinbutton_y1.Changed += new global::System.EventHandler (this.OnSpinbuttonY1Changed);
			this.spinbutton_x2.Changed += new global::System.EventHandler (this.OnSpinbuttonX2Changed);
			this.spinbutton_x1.Changed += new global::System.EventHandler (this.OnSpinbuttonX1Changed);
		}
	}
}
