
// This file has been generated by the GUI designer. Do not modify.
namespace BBB
{
	public partial class imageSize
	{
		private global::Gtk.HBox hbox3;
		private global::Gtk.CheckButton checkbutton12;
		private global::Gtk.Label label9;
		private global::Gtk.SpinButton spinbutton7;
		private global::Gtk.Label label10;
		private global::Gtk.SpinButton spinbutton6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BBB.imageSize
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BBB.imageSize";
			// Container child BBB.imageSize.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.checkbutton12 = new global::Gtk.CheckButton ();
			this.checkbutton12.CanFocus = true;
			this.checkbutton12.Name = "checkbutton12";
			this.checkbutton12.Label = global::Mono.Unix.Catalog.GetString ("Задать размер кадра");
			this.checkbutton12.DrawIndicator = true;
			this.checkbutton12.UseUnderline = true;
			this.hbox3.Add (this.checkbutton12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.checkbutton12]));
			w1.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Ширина");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbutton7 = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spinbutton7.CanFocus = true;
			this.spinbutton7.Name = "spinbutton7";
			this.spinbutton7.Adjustment.PageIncrement = 10D;
			this.spinbutton7.ClimbRate = 1D;
			this.spinbutton7.Numeric = true;
			this.hbox3.Add (this.spinbutton7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton7]));
			w3.Position = 2;
			w3.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Высота");
			this.hbox3.Add (this.label10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label10]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbutton6 = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spinbutton6.CanFocus = true;
			this.spinbutton6.Name = "spinbutton6";
			this.spinbutton6.Adjustment.PageIncrement = 10D;
			this.spinbutton6.ClimbRate = 1D;
			this.spinbutton6.Numeric = true;
			this.hbox3.Add (this.spinbutton6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton6]));
			w5.Position = 4;
			w5.Expand = false;
			this.Add (this.hbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.checkbutton12.Clicked += new global::System.EventHandler (this.OnCheckbutton12Clicked);
			this.spinbutton7.Changed += new global::System.EventHandler (this.OnSpinbutton7Changed);
			this.spinbutton6.Changed += new global::System.EventHandler (this.OnSpinbutton6Changed);
		}
	}
}
